export const MAKE_REQUEST = 'MAKE_REQUEST';
export const FAILED_REQUEST = 'FAILED_REQUEST';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';

export const ADD_STUDENT = 'ADD_STUDENT';
export const SET_RESPONSE_SUCCESS = 'SET_RESPONSE_SUCCESS';

export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';

export const GET_STUDENT_DETAILS_BY_ID = 'GET_STUDENT_DETAILS_BY_ID';